### ISSUE TITLE
Recording the data from a click event to initiate a switch to second click event

### ISSUE THREAD

**Issue by desaibh** [desaibh/Birds-Of-Paradise-Match-Game#1]
CONTEXT

WHAT USER STORY YOU ARE WORKING ON:

I am working on the user story "Listen to a Set of Click Events to Swap Cells."

WHAT YOU ARE TRYING TO DO:

I am trying to have the system record the data from one click and then compare that data to the data collected from the second click.
![screen shot 2016-09-02 at 12 40 40 pm](https://cloud.githubusercontent.com/assets/20930343/18212682/7c8f4bc4-7112-11e6-9136-b5a617b55ab3.png)

DETAILED DESCRIPTION OF THE BUG/ERROR:

I cannot record the data from the first click and the second click.

WHAT I'VE TRIED

I explored Jquery's Toggle and Data functions, but neither worked.

QUESTION
Can I store two sets of data from an onclick event?

**Comment by ddruker** [comment]
Conditionally adding event listeners
